name: actions-build-landing-app

on: 
  push:
    branches:
      - beta
      - production

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Git clone repo    
        uses: actions/checkout@v2

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
 
 
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          tags: name/app:latest,name/app:1.0.0   
        
      - name: List docker images
        run : docker ps -a

