name: actions-build-landing-app

on: push
#    branches:
#      - beta

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16    
      - run: npm install
      - run: yarn
    
      - name: List current folder
        run : ls -la
