name: actions-build-landing-app

on: 
  push:
    branches:
      - beta
      - production

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Git clone repo    
        uses: actions/checkout@v2
        
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          registry: ghcr.io
        
        
      - name: List docker images
        run : docker ps -a

